version: '3.8'
services:
  web:
    build: .
    ports:
      - "86:80"
    environment:
      - SQL_SERVEUR=db
      - SQL_BASE=medshakest
      - SQL_USER=user
      - SQL_PASS=password
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medshakest
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data_sql:/docker-entrypoint-initdb.d/


